import type { Metadata } from "next";
import "./globals.scss";
import { AuthHandler, useAuth } from "./Components/AuthHandler";
import Navbar from "./Components/Layout/Navbar";



export const metadata: Metadata = {
  title: "Urban P2: The Archives",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthHandler>
        <Navbar />
        {children}
        </AuthHandler>
      </body>
    </html>
  );
}

