import type { Metadata } from "next";
import Image from "next/image";
import "./globals.scss";


export const metadata: Metadata = {
  title: "Urban P2: The Archives",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}


const Navbar = () => {

  return (<nav>
    <Image src="/urbanp2.jpeg" alt="Logo" width={100} height={100} />
    <h1>Urban P2: The Archives</h1>
  </nav>)

}